# Generated by Django 2.1.2 on 2021-03-10 19:59

import dashboard.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetType', models.TextField()),
                ('assetRegistrationId', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('personId', models.CharField(default=dashboard.utils.generate_person_ID, max_length=10, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('phone', models.CharField(max_length=10)),
                ('email', models.TextField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationLong', models.DecimalField(decimal_places=16, max_digits=19)),
                ('locationLat', models.DecimalField(decimal_places=16, max_digits=19)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('tripId', models.CharField(default=dashboard.utils.generate_trip_ID, max_length=12, primary_key=True, serialize=False)),
                ('srcLong', models.DecimalField(decimal_places=16, max_digits=19)),
                ('srcLat', models.DecimalField(decimal_places=16, max_digits=19)),
                ('desLong', models.DecimalField(decimal_places=16, max_digits=19)),
                ('desLat', models.DecimalField(decimal_places=16, max_digits=19)),
                ('time', models.DecimalField(decimal_places=4, max_digits=8)),
                ('asset', models.ForeignKey(default=dashboard.utils.generate_default_asset_ID, on_delete=django.db.models.deletion.SET_DEFAULT, to='dashboard.Asset')),
            ],
        ),
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('stopId', models.CharField(default=dashboard.utils.generate_stop_ID, max_length=12, primary_key=True, serialize=False)),
                ('locationLat', models.DecimalField(decimal_places=16, max_digits=19)),
                ('locationLon', models.DecimalField(decimal_places=16, max_digits=19)),
                ('order', models.IntegerField()),
                ('trip', models.ForeignKey(default=dashboard.utils.generate_default_trip_ID, on_delete=django.db.models.deletion.SET_DEFAULT, to='dashboard.Trip')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicleName', models.TextField()),
                ('vehicleId', models.CharField(default=dashboard.utils.generate_vehicle_ID, max_length=10, primary_key=True, serialize=False)),
                ('company', models.TextField()),
            ],
        ),
    ]
