# Generated by Django 2.1.2 on 2021-03-13 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='locationLat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='locationLong',
            new_name='longitude',
        ),
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
