# Generated by Django 2.1.2 on 2021-03-13 11:36

import dashboard.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210313_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='assetId',
            field=models.CharField(default=dashboard.utils.generate_default_asset_ID, max_length=10),
        ),
    ]
