# Generated by Django 2.1.2 on 2021-03-17 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_position_assetid'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='latitude',
            field=models.DecimalField(decimal_places=16, default=27.218848985295054, max_digits=19),
        ),
        migrations.AddField(
            model_name='asset',
            name='longitude',
            field=models.DecimalField(decimal_places=16, default=77.50081190185514, max_digits=19),
        ),
        migrations.AddField(
            model_name='asset',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 18, 0, 17, 33, 648187)),
        ),
    ]
