# Generated by Django 3.1.7 on 2021-03-20 02:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210318_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='latitude',
            field=models.DecimalField(decimal_places=16, default=27.200334727931867, max_digits=19),
        ),
        migrations.AlterField(
            model_name='asset',
            name='longitude',
            field=models.DecimalField(decimal_places=16, default=77.49520608628461, max_digits=19),
        ),
        migrations.AlterField(
            model_name='asset',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 20, 8, 7, 48, 156918)),
        ),
    ]
