# Generated by Django 3.1.7 on 2021-03-23 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20210320_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='latitude',
            field=models.DecimalField(decimal_places=16, default=27.213609152520796, max_digits=19),
        ),
        migrations.AlterField(
            model_name='asset',
            name='longitude',
            field=models.DecimalField(decimal_places=16, default=77.49516989009078, max_digits=19),
        ),
        migrations.AlterField(
            model_name='asset',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 23, 19, 38, 25, 658712)),
        ),
    ]
