# Generated by Django 2.1.2 on 2021-04-03 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20210401_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='endTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 3, 11, 10, 56, 627662)),
        ),
        migrations.AlterField(
            model_name='asset',
            name='latitude',
            field=models.DecimalField(decimal_places=16, default=27.20300559886818, max_digits=19),
        ),
        migrations.AlterField(
            model_name='asset',
            name='longitude',
            field=models.DecimalField(decimal_places=16, default=77.50687728098006, max_digits=19),
        ),
        migrations.AlterField(
            model_name='asset',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 3, 11, 10, 56, 625663)),
        ),
    ]
