# Generated by Django 2.1.2 on 2021-04-03 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20210403_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='latitude',
            field=models.DecimalField(decimal_places=16, default=27.202864875435292, max_digits=19),
        ),
        migrations.AlterField(
            model_name='asset',
            name='longitude',
            field=models.DecimalField(decimal_places=16, default=77.50034002938165, max_digits=19),
        ),
        migrations.AlterField(
            model_name='asset',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 3, 13, 4, 9, 442851)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 3, 13, 4, 9, 444851)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='time',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True),
        ),
    ]
